//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yurt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class misafirler
    {
        public int mis_id { get; set; }
        public string mis_tcPas { get; set; }
        public string mis_ad { get; set; }
        public string mis_soyad { get; set; }
        public string mis_cinsiyet { get; set; }
        public string mis_uyruk { get; set; }
        public string mis_tel { get; set; }
        public Nullable<System.DateTime> mis_giris { get; set; }
        public Nullable<System.DateTime> mis_cikis { get; set; }
        public Nullable<int> mis_kgun { get; set; }
        public Nullable<int> mis_yatakucret { get; set; }
        public Nullable<int> mis_borc { get; set; }
    }
}
