//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yurt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class YurtOtomasyonEntities : DbContext
    {
        public YurtOtomasyonEntities()
            : base("name=YurtOtomasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<misafirler> misafirler { get; set; }
        public virtual DbSet<odalar> odalar { get; set; }
        public virtual DbSet<ogrenciler> ogrenciler { get; set; }
        public virtual DbSet<tahsilatlar> tahsilatlar { get; set; }
        public virtual DbSet<yataklar> yataklar { get; set; }
        public virtual DbSet<yetkililer> yetkililer { get; set; }
    
        public virtual ObjectResult<SP_hepsiniSil_Result> SP_hepsiniSil()
        {
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_hepsiniSil_Result>("SP_hepsiniSil");
        }
    }
}
