//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yurt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ogrenciler()
        {
            this.tahsilatlar = new HashSet<tahsilatlar>();
        }
    
        public int ogr_id { get; set; }
        public string ogr_tcPas { get; set; }
        public string ogr_ad { get; set; }
        public string ogr_soyad { get; set; }
        public string ogr_cinsiyet { get; set; }
        public string ogr_kan { get; set; }
        public string ogr_uyruk { get; set; }
        public string ogr_tel { get; set; }
        public string ogr_email { get; set; }
        public string ogr_adres { get; set; }
        public string ogr_egitim { get; set; }
        public Nullable<int> oda_id { get; set; }
    
        public virtual odalar odalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tahsilatlar> tahsilatlar { get; set; }
    }
}
