//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yurt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tahsilatlar
    {
        public int tah_id { get; set; }
        public Nullable<int> tah_ogrID { get; set; }
        public string tah_tutar { get; set; }
        public Nullable<System.DateTime> tah_sontarih { get; set; }
        public string tah_durum { get; set; }
    
        public virtual ogrenciler ogrenciler { get; set; }
    }
}
