//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yurt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yetkililer
    {
        public int yet_id { get; set; }
        public string yet_kullaniciAd { get; set; }
        public string yet_sifre { get; set; }
        public string yet_tel { get; set; }
        public string yet_email { get; set; }
    }
}
